/**
 * lib/storage.ts
 *
 * ┌─────────────────────────────────────────────────────────────────────────┐
 * │  THE SINGLE GATEWAY TO SUPABASE                                         │
 * │                                                                         │
 * │  This file is the ONLY place in the codebase that:                     │
 * │    - imports from lib/supabase.ts                                       │
 * │    - reads or writes to any Supabase table                              │
 * │    - knows about snake_case database column names                       │
 * │                                                                         │
 * │  Everything else (API routes, hooks, components) imports only:          │
 * │    import { storage } from "@/lib/storage"                              │
 * │                                                                         │
 * │  To add a new provider (Redis, PlanetScale, etc.):                     │
 * │    1. Create a class implementing LinkStorage                           │
 * │    2. Change the export at the bottom — one line                        │
 * │    3. Zero changes to API routes, hooks, or components                  │
 * └─────────────────────────────────────────────────────────────────────────┘
 *
 * ARCHITECTURE
 * ─────────────
 *
 *  types/index.ts          → LinkStorage interface (the contract)
 *  lib/database.types.ts   → Raw Supabase row shapes (DbLink, etc.)
 *  lib/supabase.ts         → Supabase client singleton
 *  lib/storage.ts          → SupabaseStorage implements LinkStorage  ← YOU ARE HERE
 *
 *  API routes              → import { storage } from "@/lib/storage"
 *  Hooks / components      → call API routes, never import storage directly
 */

import { supabase } from "@/lib/supabase";
import type { DbLink, DbLinkInsert } from "@/lib/database.types";
import type {
  Link,
  LinkStorage,
  CreateLinkPayload,
  UpdateLinkPayload,
  LinkCategory,
} from "@/types";

// ─────────────────────────────────────────────────────────────────────────────
// Row mapper: DatabaseLink (snake_case) → Link (camelCase)
//
// This is the only place that knows the DB uses `created_at` while
// the app uses `createdAt`. Keeping this isolated means schema renames
// only require updating this function.
// ─────────────────────────────────────────────────────────────────────────────

function toLink(row: DbLink): Link {
  return {
    id:          row.id,
    title:       row.title,
    url:         row.url,
    description: row.description ?? "",
    category:    row.category as LinkCategory,
    tags:        row.tags ?? [],
    createdAt:   row.created_at,
    updatedAt:   row.updated_at,
    userId:      row.user_id,
    isPublic:    row.is_public,
    metadata:    row.metadata as Record<string, unknown> | null,
  };
}

// ─────────────────────────────────────────────────────────────────────────────
// SupabaseStorage
// ─────────────────────────────────────────────────────────────────────────────

class SupabaseStorage implements LinkStorage {

  // ── getLinks ──────────────────────────────────────────────────────────────

  async getLinks(): Promise<Link[]> {
    const { data, error } = await supabase
      .from("links")
      .select("*")
      .order("created_at", { ascending: false });

    if (error) throw new StorageError("getLinks", error.message);
    return (data ?? []).map(toLink);
  }

  // ── getLink ───────────────────────────────────────────────────────────────

  async getLink(id: string): Promise<Link | null> {
    const { data, error } = await supabase
      .from("links")
      .select("*")
      .eq("id", id)
      .maybeSingle();           // returns null instead of error when not found

    if (error) throw new StorageError("getLink", error.message);
    return data ? toLink(data) : null;
  }

  // ── addLink ───────────────────────────────────────────────────────────────

  async addLink(payload: CreateLinkPayload): Promise<Link> {
    const insert: DbLinkInsert = {
      title:       payload.title.trim(),
      url:         payload.url.trim(),
      description: payload.description?.trim() ?? null,
      category:    payload.category,
      tags:        payload.tags ?? [],
      is_public:   payload.isPublic ?? false,
      metadata:    payload.metadata ?? null,
      // id, created_at, updated_at — generated by Supabase defaults
    };

    const { data, error } = await supabase
      .from("links")
      .insert(insert)
      .select()
      .single();

    if (error) throw new StorageError("addLink", error.message);
    return toLink(data);
  }

  // ── updateLink ────────────────────────────────────────────────────────────

  async updateLink(id: string, payload: UpdateLinkPayload): Promise<Link> {
    // Build update object — only include fields that were supplied
    const update: Record<string, unknown> = {
      updated_at: new Date().toISOString(),
    };

    if (payload.title       !== undefined) update.title       = payload.title.trim();
    if (payload.url         !== undefined) update.url         = payload.url.trim();
    if (payload.description !== undefined) update.description = payload.description.trim();
    if (payload.category    !== undefined) update.category    = payload.category;
    if (payload.tags        !== undefined) update.tags        = payload.tags;
    if (payload.isPublic    !== undefined) update.is_public   = payload.isPublic;
    if (payload.metadata    !== undefined) update.metadata    = payload.metadata;

    const { data, error } = await supabase
      .from("links")
      .update(update)
      .eq("id", id)
      .select()
      .single();

    if (error) {
      // Supabase returns PGRST116 when no rows matched
      if (error.code === "PGRST116") throw new NotFoundError(id);
      throw new StorageError("updateLink", error.message);
    }

    return toLink(data);
  }

  // ── deleteLink ────────────────────────────────────────────────────────────

  async deleteLink(id: string): Promise<void> {
    const { error } = await supabase
      .from("links")
      .delete()
      .eq("id", id);

    if (error) throw new StorageError("deleteLink", error.message);
  }

  // ── exportLinks ───────────────────────────────────────────────────────────
  //
  // Returns all links as a typed array. The API route (/api/export) is
  // responsible for serializing and streaming the response as a download.
  // Storage concerns itself only with fetching — not formatting.

  async exportLinks(): Promise<Link[]> {
    return this.getLinks();
  }
}

// ─────────────────────────────────────────────────────────────────────────────
// Custom errors
//
// Typed errors let API routes respond with correct HTTP status codes
// without knowing anything about Supabase internals.
// ─────────────────────────────────────────────────────────────────────────────

export class StorageError extends Error {
  constructor(operation: string, detail: string) {
    super(`[storage.${operation}] ${detail}`);
    this.name = "StorageError";
  }
}

export class NotFoundError extends Error {
  constructor(id: string) {
    super(`Link not found: ${id}`);
    this.name = "NotFoundError";
  }
}

// ─────────────────────────────────────────────────────────────────────────────
// Export — change this one line to swap the entire storage backend
// ─────────────────────────────────────────────────────────────────────────────

export const storage: LinkStorage = new SupabaseStorage();
